export enum ERROR_TEXTS {
  GENERIC_ERROR = "Ha ocurrido un error. Por favor, intenta de nuevo.",
  GENERIC_INVALID_FIELD = "Por favor, corrige el campo.",
  INTERNAL_SERVER_ERROR = "¡Oops, ocurrió un error. Por favor, intenta de nuevo!",
  REQUIRED_FIELD = "Completa los campos requeridos",
  INVALID_LETTERS_FIELD = "El campo solo puede contener letras",
  INVALID_ALPHANUMERIC_FIELD = "El campo solo puede contener letras y números",
  INVALID_EMAIL_FIELD = "Formato de correo inválido",
  INVALID_PASSWORD_FIELD = "Formato de contraseña incorrecto",
  ALERT_REQUIRED_FIELD = "Por favor, completa los campos requeridos.",
  INVALID_PASSWORDS_MATCH_FIELD = "Las contraseñas no coinciden",
  INVALID_PASSWORDS_MATCH_ALERT = "Las contraseña no coinciden. Por favor, corrige y vuelve a intentar",
  INVALID_BIRTH_DATE = "Debes ser mayor de 13 años y proporcionar una fecha válida",
  INVALID_FORM_DATA = "Por favor verifica los datos del formulario",
  INVALID_BIRTH_DATE_ALERT = "Por favor verifica la fecha de nacimiento",
  INVALID_EMAIL_ALERT = "Por favor ingresa un email válido",
  INVALID_PASSWORD_LENGTH = "La contraseña debe tener al menos 8 caracteres",
  INVALID_AGE_ALERT = "Debes ser mayor de 13 años para registrarte",
  EXISTING_EMAIL = "El correo electrónico ingresado ya existe.",
  UNEXISTING_USER = "El correo electronico ingresado no existe",
  INVALID_CODE = "El código ingresado es inválido.",
  EXISTING_CODE = "El código ingresado ya ha sido utilizado.",
  USER_NOT_VERIFIED = "El usuario aún no ha sido verificado",
  RESEND_CODE_ERROR = "Error al reenviar el código de verificación",
}
